# Mode 1 - Always raining. Air always toxic.
# Mode 2 - Rains now and then (like normal). Air always toxic.
# Mode 3 - Rains now and then (like normal). Air only toxic when raining.
Mode: 1

SecondsBetweenPolls: 10
AboveGroundDamage: 1
AboveGroundMessage: The air burns your lungs and saps your strength!
PumpkinHelmetBreakChancePercent: 8
PumpkinHelmetBreakMessage: Your pumpkin helmet falls apart in your hands!
PumpkinHelmetSurviveMessage: Your pumpkin helmet weakens.
AffectedWorlds:
- world